; generated by /home/matt/dev/ereaderz80/src/solitaire/scripts/generateCardDefs.ts




CARD_TURNED_OVER_MASK = 0x80


; if you like to gamble, I tell you I'm your man...
S_A = 0x01 ; A of Spades
S_2 = 0x02 ; 2 of Spades
S_3 = 0x03 ; 3 of Spades
S_4 = 0x04 ; 4 of Spades
S_5 = 0x05 ; 5 of Spades
S_6 = 0x06 ; 6 of Spades
S_7 = 0x07 ; 7 of Spades
S_8 = 0x08 ; 8 of Spades
S_9 = 0x09 ; 9 of Spades
S_10 = 0x0a; 10 of Spades
S_J = 0x0b ; J of Spades
S_Q = 0x0c ; Q of Spades
S_K = 0x0d ; K of Spades

H_A = 0x0e ; A of Hearts
H_2 = 0x0f ; 2 of Hearts
H_3 = 0x10 ; 3 of Hearts
H_4 = 0x11 ; 4 of Hearts
H_5 = 0x12 ; 5 of Hearts
H_6 = 0x13 ; 6 of Hearts
H_7 = 0x14 ; 7 of Hearts
H_8 = 0x15 ; 8 of Hearts
H_9 = 0x16 ; 9 of Hearts
H_10 = 0x17; 10 of Hearts
H_J = 0x18 ; J of Hearts
H_Q = 0x19 ; Q of Hearts
H_K = 0x1a ; K of Hearts

C_A = 0x1b ; A of Clubs
C_2 = 0x1c ; 2 of Clubs
C_3 = 0x1d ; 3 of Clubs
C_4 = 0x1e ; 4 of Clubs
C_5 = 0x1f ; 5 of Clubs
C_6 = 0x20 ; 6 of Clubs
C_7 = 0x21 ; 7 of Clubs
C_8 = 0x22 ; 8 of Clubs
C_9 = 0x23 ; 9 of Clubs
C_10 = 0x24; 10 of Clubs
C_J = 0x25 ; J of Clubs
C_Q = 0x26 ; Q of Clubs
C_K = 0x27 ; K of Clubs

D_A = 0x28 ; A of Diamonds
D_2 = 0x29 ; 2 of Diamonds
D_3 = 0x2a ; 3 of Diamonds
D_4 = 0x2b ; 4 of Diamonds
D_5 = 0x2c ; 5 of Diamonds
D_6 = 0x2d ; 6 of Diamonds
D_7 = 0x2e ; 7 of Diamonds
D_8 = 0x2f ; 8 of Diamonds
D_9 = 0x30 ; 9 of Diamonds
D_10 = 0x31; 10 of Diamonds
D_J = 0x32 ; J of Diamonds
D_Q = 0x33 ; Q of Diamonds
D_K = 0x34 ; K of Diamonds
